# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(500, 300)
        self.centralwidget = QtWidgets.QWidget(Form)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 0, 0, 1, 1)
        Form.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Form)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuFormat = QtWidgets.QMenu(self.menubar)
        self.menuFormat.setObjectName("menuFormat")
        Form.setMenuBar(self.menubar)
        self.actionNew = QtWidgets.QAction(Form)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(Form)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(Form)
        self.actionSave.setObjectName("actionSave")
        self.actionSaveAs = QtWidgets.QAction(Form)
        self.actionSaveAs.setObjectName("actionSaveAs")
        self.actionExit = QtWidgets.QAction(Form)
        self.actionExit.setObjectName("actionExit")
        self.actionBold = QtWidgets.QAction(Form)
        self.actionBold.setCheckable(True)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.actionBold.setFont(font)
        self.actionBold.setObjectName("actionBold")
        self.actionItalic = QtWidgets.QAction(Form)
        self.actionItalic.setCheckable(True)
        font = QtGui.QFont()
        font.setItalic(True)
        self.actionItalic.setFont(font)
        self.actionItalic.setObjectName("actionItalic")
        self.actionUnderline = QtWidgets.QAction(Form)
        self.actionUnderline.setCheckable(True)
        font = QtGui.QFont()
        font.setUnderline(True)
        self.actionUnderline.setFont(font)
        self.actionUnderline.setObjectName("actionUnderline")
        self.actionStrikeOut = QtWidgets.QAction(Form)
        self.actionStrikeOut.setCheckable(True)
        font = QtGui.QFont()
        font.setStrikeOut(True)
        self.actionStrikeOut.setFont(font)
        self.actionStrikeOut.setObjectName("actionStrikeOut")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSaveAs)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuFormat.addAction(self.actionBold)
        self.menuFormat.addAction(self.actionItalic)
        self.menuFormat.addAction(self.actionUnderline)
        self.menuFormat.addAction(self.actionStrikeOut)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuFormat.menuAction())

        self.retranslateUi(Form)
        self.actionExit.triggered.connect(Form.close)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Text Editor"))
        self.menuFile.setTitle(_translate("Form", "&File"))
        self.menuFormat.setTitle(_translate("Form", "F&ormat"))
        self.actionNew.setText(_translate("Form", "&New"))
        self.actionNew.setShortcut(_translate("Form", "Ctrl+N"))
        self.actionOpen.setText(_translate("Form", "&Open"))
        self.actionOpen.setShortcut(_translate("Form", "Ctrl+O"))
        self.actionSave.setText(_translate("Form", "&Save"))
        self.actionSave.setShortcut(_translate("Form", "Ctrl+S"))
        self.actionSaveAs.setText(_translate("Form", "Save &As"))
        self.actionSaveAs.setShortcut(_translate("Form", "F12"))
        self.actionExit.setText(_translate("Form", "E&xit"))
        self.actionBold.setText(_translate("Form", "&Bold"))
        self.actionBold.setShortcut(_translate("Form", "Ctrl+B"))
        self.actionItalic.setText(_translate("Form", "&Italic"))
        self.actionItalic.setShortcut(_translate("Form", "Ctrl+I"))
        self.actionUnderline.setText(_translate("Form", "&Underline"))
        self.actionUnderline.setShortcut(_translate("Form", "Ctrl+U"))
        self.actionStrikeOut.setText(_translate("Form", "S&trikeout"))
        self.actionStrikeOut.setShortcut(_translate("Form", "Ctrl+T"))

